### ISSUE TITLE
Single command vs multiple

### ISSUE THREAD

**Issue by ToxicBakery** [DFieldFL/slack-beer-search-bot#4]
Personally I would like a single command or interface to the system instead of needing to remember multiple root commands.

Currently the commands are:
/beer [beer id]
/beerSearch [name of beer]
/botw

I would propose that the root command simply be 'beer' and all sub commands route from it.
- Renaming
  - /beer [beer id]
  - /beer search [name of beer]
  - /beer botw
  - /beer help
- Future?
  - /beer random
  - /beer random [ipa,stout,lager,etc]

I think this helps break down my suggestion while also providing possible future features. (I know you are limited by the API so they may not be feasible.)

**Comment by DFieldFL** [comment]
This sounds good and it should save people from using multiple slack commands/integrations.

**Comment by DFieldFL** [comment]
fixed
